Update manual.yml

diff --git a/.github/workflows/manual.yml b/.github/workflows/manual.yml
--- a/.github/workflows/manual.yml
+++ b/.github/workflows/manual.yml
@@ -16,9 +16,13 @@ jobs:
         with:
           java-version: 17
           distribution: 'temurin'
+          cache: 'maven'
 
       - name: Run Maven tests
-        run: mvn test
+        run: mvn -B clean test
+
+      - name: Show Maven repository contents
+        run: ls -R ~/.m2/repository/org/apache/maven/plugins/maven-surefire-plugin || echo "Surefire not found"
 
       - name: Upload JUnit results to Xray (Jira)
         env:
